add data science exercise
miguelsimon/ejercicios pull request #33
Opened 2023-03-31 12:05 UTC by miguelsimon

This is meant as a simple exercise to hone data science related skills, namely:

* transforming data using basic sql
* using basic visualizations to understand the data
* understanding what an observational study is
* the dangers of jumping to causal conclusions when interpreting observational studies

2023-04-01 17:50 UTC, valentinboyanov requested changes
I've been able to understand the exercise, links work and columns and data seem to be OK:

```
data_science_1 git:(data_science_1) sqlite3
SQLite version 3.39.5 2022-10-14 20:58:05
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> .read dataset_3.sql
sqlite> .tables
ages                 exercise             pediatric          
data_collection_day  participants         thanatol           
sqlite> .headers on
sqlite> select * from ages limit 1;
id|birthday
767|2005-04-04
sqlite> select count(*) from ages;
count(*)
963
sqlite> select * from exercise limit 1;
id|hours_per_week
767|5.89889879900017
sqlite> select count(*) from exercise;
count(*)
963
sqlite> select * from participants limit 1;
id
0
sqlite> select count(*) from participants;
count(*)
963
sqlite> select * from data_collection_day limit 1;
data_collection_day
2023-03-31
sqlite> select count(*) from data_collection_day;
count(*)
1
sqlite> select * from thanatol limit 1;
id|mmol_per_l
767|14.3373875132598
sqlite> select count(*) from thanatol;
count(*)
963
sqlite> select * from pediatric limit 1;
age|hours_per_day|mmol_per_l
16.0|0.834732072023712|14.1136291834294
sqlite> select count(*) from pediatric;
count(*)
37
sqlite> 
```

I've found only one minor formatting issue, otherwise lgtm!

2023-04-01 17:50 UTC, valentinboyanov commented on data_science_1/README.md
> +* age: edad del participante en años en el momento del estudio
Minor formatting consistency issue about column names, eg: `age` will be consistent.

2023-04-01 17:59 UTC, valentinboyanov commented
Not so related to this PR, but I've noticed that the main index is somewhat inconsistent:

https://github.com/miguelsimon/ejercicios/blob/7eae227f11ffe59a6b62285fd3d7a2297e9738fa/README.md?plain=1#L7-L21

2023-04-02 06:02 UTC, miguelsimon commented
I've noticed the inconsistency in the main index too but I'm leaving it alone for now as I don't really have a good idea for a unifying style yet.

2023-04-02 06:11 UTC, valentinboyanov approved these changes
lgtm!

2023-04-02 06:19 UTC, merged